---

version: "3.7"

services:
  app:
    working_dir: /app
    command: ./startup.sh
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    environment:
      - TZ=Asia/Tokyo
    ports:
      - 80:3000
    volumes:
      - .:/app
    links:
      - postgres:postgres

  postgres:
    image: postgres:11.2
    environment:
      - TZ=Asia/Tokyo
    ports:
      - 5432:5432
